let bingoItems = [
    'Ruling company loses Everfall and subsequently falls apart',
    'Ruling company loses Windsward and subsequently falls apart',
    'Someone creates a server-wide discord',
    'Someone creates a new discord after being ostracized from the first discord',
    'A notable person is caught stealing company funds',
    'Somebody tries to orchestrate a company / faction coup',
    'Somebody reaches 200 Furnishing',
    'Somebody clocks 600 hours of play time',
    'Game-breaking bug discovered',
    'Joe Biden memes in Global chat',
    'Somebody reaches 600GS',
    'Somebody playing music in town is berated in proximity chat',
    'A company governor / consul is harassed into quitting the game',
    'Ruling faction splinters due to drama',
    'You are verbally assaulted after winning a 1v1',
    'You are verbally assaulted after losing a 1v1',
    'Proximity chat used to play horrible music',
    'A /dice gambling ring forms',
    'A company of veteran players joins the server to shit on new players',
    'A territory flips 3 times in 7 days',
    'Nobody defends Reekwater',
    'Somebody programs a discord bot',
    'Somebody uses their house to display expletives to everyone in Everfall',
    'Daily player counts down 50% from peak',
    'Faction alliance falls apart within 2 weeks of forming',
    'Town flips and new company maxes out taxes',
    'There is a mass exodus from one faction to another',
    'Bots are back',
    'Dramalord claims to hate drama',
    'Somebody makes a reference to the giant sausage',
    'A notable person is banned from the game',
    'Somebody corners the market',
    'The company that claims the first territory loses it',
    'Somebody makes a New World drama calendar',
    'A sweatlord company advertises themselves as mercenaries',
    'Someone spams their Twitch in Global chat',
    'Streamer appears on server',
    'One company buys two territories',
]
export default bingoItems;